dittofund_renewal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('index/', include('index.urls', namespace='index')),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
]

index/urls.py
from django.urls import path

from index.views import Index, CompareView, PortfolioList, HedgefundList, HedgefundDetail, PortfolioDetail, \
    PortfolioCreate

app_name = 'index'

urlpatterns = [
    path('', Index.as_view(), name='intro'),
    path('hedgefund/', HedgefundList.as_view(), name='hedgefund'),
    path('hedgefund/<int:pk>/', HedgefundDetail.as_view()),
    path('portfolio/', PortfolioList.as_view(), name='portfolio'),
    path('portfolio/<int:pk>/', PortfolioDetail.as_view()),
    path('create_portfolio/', PortfolioCreate.as_view()),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>Dittofund</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/de33348239.js" crossorigin="anonymous"></script>
</head>
<body>
{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Dittofund</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="{% url 'index:hedgefund' %}">Hedgefund</a>
                    <a class="nav-link" href="{% url 'index:portfolio' %}">Portfolio</a>
                </div>
            </div>
        </div>
    </nav>
{% endblock navbar %}
{% block content %}

{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
    <div class="container">
        <div class="h1 my-5">Dittofund Index Page</div>
        <div class="h1">디토펀드란?</div>
        <div class="h5">
            <p>- Ditto는 우리에게 메타몽 이라는 이름으로 알려진 포켓몬입니다. 남의 모습을 복사하는 능력을 갖고 있죠.</p>
            <p>- Fund는 우리가 잘 아는 투자상품의 펀드도 있지만 여기서는 헤지펀드를 말합니다.</p>
        </div>
        <div class="h3 my-4">
            미국은 분기별로 헤지펀드의 포트폴리오를 정부에 공개해야 하는 법을 시행하고 있습니다.
        </div>
        <div class="h5">
            <p>- 이 말은 실시간은 아니지만 분기별로는 모든 헤지펀드들의 포트폴리오의 변동을 파악할 수 있다는 말이죠.</p>
            <p>- 만약 우리가 워렌 버핏의 포트폴리오를 따라할 수 있다면, 버핏만큼은 아니겠지만 그래도 어느 정도는 버핏과 유사한 형태의 이익을 얻을 수 있겠죠?</p>
            <p>- Dittofund는 그런 유형의 투자를 할 때 참고자료를 제공해주는 서비스입니다.</p>
        </div>
    </div>
{% endblock %}